# This is a Bitbucket Pipelines build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.5.2

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - pip install -r requirements.txt
          - make clean test doc
          - bin/decompile examples/dao_hack.dasm
          - bin/decompile examples/mem_leak.dasm
          - bin/decompile examples/withdraw_dao.dasm